# experiment name
note: train

#project basic
task: reconstruction  # interVAE reconstruction

#model basic
gpu_index: 0
lr: 0.0001
batchsize: 32
frame_length: 16
epoch: 2000
worker: 10
use_sch: True
model_type: smpl

#********dataset*********#
# The path for datasets and annotations
data_folder: data/dataset
output: output

trainset: Hi4D
testset: Hi4D

# cliff hmr cliff_hmr pose_transformer_v8  relation relation_v8
model: pose_prediction
use_prior: False

mode: train # train/test/eval


# Use pretrain model and the corresponding path
pretrain: False
pretrain_dir: data/checkpoint.pkl


# The name of your training loss function
# Split different names with a single space
# e.g., KL_Loss MPJPE L1 L2
train_loss: Seg_Sig_Loss Pose_Loss Mesh_Loss
test_loss: Seg_Sig_Iou MPJPE PA_MPJPE

#visualize
viz: False
